export const developers = [
  {
    rank: 1,
    username: "klauspost",
    name: "Klaus Post",
    url: "https://github.com/klauspost",
    avatar: "https://avatars.githubusercontent.com/u/5663952?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "compress",
      description: "Optimized Go Compression Packages",
      url: "https://github.com/klauspost/compress",
    },
  },
  {
    rank: 2,
    username: "phil-opp",
    name: "Philipp Oppermann",
    url: "https://github.com/phil-opp",
    avatar: "https://avatars.githubusercontent.com/u/1131315?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "blog_os",
      description: "Writing an OS in Rust",
      url: "https://github.com/phil-opp/blog_os",
    },
  },
  {
    rank: 3,
    username: "Kethku",
    name: "Keith Simmons",
    url: "https://github.com/Kethku",
    avatar: "https://avatars.githubusercontent.com/u/3323631?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "neovide",
      description: "No Nonsense Neovim Client in Rust",
      url: "https://github.com/Kethku/neovide",
    },
  },
  {
    rank: 4,
    username: "samtstern",
    name: "Sam Stern",
    url: "https://github.com/samtstern",
    avatar: "https://avatars.githubusercontent.com/u/8466666?s=96&v=4",
    since: "daily",
    popularRepository: { repositoryName: null, description: null, url: null },
  },
  {
    rank: 5,
    username: "mfussenegger",
    name: "Mathias Fußenegger",
    url: "https://github.com/mfussenegger",
    avatar: "https://avatars.githubusercontent.com/u/38700?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "nvim-dap",
      description:
        "Debug Adapter Protocol client implementation for Neovim (>= 0.5)",
      url: "https://github.com/mfussenegger/nvim-dap",
    },
  },
  {
    rank: 6,
    username: "mislav",
    name: "Mislav Marohnić",
    url: "https://github.com/mislav",
    avatar: "https://avatars.githubusercontent.com/u/887?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "will_paginate",
      description:
        "Pagination library for Rails, Sinatra, Merb, DataMapper, and more",
      url: "https://github.com/mislav/will_paginate",
    },
  },
  {
    rank: 7,
    username: "rom1v",
    name: "Romain Vimont",
    url: "https://github.com/rom1v",
    avatar: "https://avatars.githubusercontent.com/u/543275?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "sndcpy",
      description: "Android audio forwarding (scrcpy, but for audio)",
      url: "https://github.com/rom1v/sndcpy",
    },
  },
  {
    rank: 8,
    username: "PySimpleGUI",
    name: "PySimpleGUI",
    url: "https://github.com/PySimpleGUI",
    avatar: "https://avatars.githubusercontent.com/u/46163555?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "PySimpleGUI",
      description:
        "Launched in 2018 Actively developed and supported. Supports tkinter, Qt, WxPython, Remi (in browser). Create custom layout GUI's simply. Python 2.7 & 3 Support. 200+ Demo programs & Cookbook for rapid start. Extensive documentation. Examples using Machine Learning(GUI, OpenCV Integration, Chatterbot), Floating Desktop Widgets, Matplotlib + Pyplo…",
      url: "https://github.com/PySimpleGUI/PySimpleGUI",
    },
  },
  {
    rank: 9,
    username: "dunglas",
    name: "Kévin Dunglas",
    url: "https://github.com/dunglas",
    avatar: "https://avatars.githubusercontent.com/u/57224?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "symfony-docker",
      description:
        "A Docker-based installer and runtime for Symfony. Install: download and `docker-compose up`.",
      url: "https://github.com/dunglas/symfony-docker",
    },
  },
  {
    rank: 10,
    username: "tkf",
    name: "Takafumi Arakaki",
    url: "https://github.com/tkf",
    avatar: "https://avatars.githubusercontent.com/u/29282?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "ConcurrentCollections.jl",
      description: "Concurrent data structures for Julia (WIP)",
      url: "https://github.com/tkf/ConcurrentCollections.jl",
    },
  },
  {
    rank: 11,
    username: "vis2k",
    name: "vis2k",
    url: "https://github.com/vis2k",
    avatar: "https://avatars.githubusercontent.com/u/16416509?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "Mirror",
      description: "#1 Open Source Unity Networking Library",
      url: "https://github.com/vis2k/Mirror",
    },
  },
  {
    rank: 12,
    username: "frenck",
    name: "Franck Nijhof",
    url: "https://github.com/frenck",
    avatar: "https://avatars.githubusercontent.com/u/195327?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "awesome-home-assistant",
      description:
        "A curated list of amazingly awesome Home Assistant resources.",
      url: "https://github.com/frenck/awesome-home-assistant",
    },
  },
  {
    rank: 13,
    username: "JanDeDobbeleer",
    name: "Jan De Dobbeleer",
    url: "https://github.com/JanDeDobbeleer",
    avatar: "https://avatars.githubusercontent.com/u/2492783?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "oh-my-posh",
      description: "A prompt theme engine for any shell.",
      url: "https://github.com/JanDeDobbeleer/oh-my-posh",
    },
  },
  {
    rank: 14,
    username: "XhmikosR",
    name: "XhmikosR",
    url: "https://github.com/XhmikosR",
    avatar: "https://avatars.githubusercontent.com/u/349621?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "notepad2-mod",
      description:
        "LOOKING FOR DEVELOPERS - Notepad2-mod, a Notepad2 fork, a fast and light-weight Notepad-like text editor with syntax highlighting",
      url: "https://github.com/XhmikosR/notepad2-mod",
    },
  },
  {
    rank: 15,
    username: "me-no-dev",
    name: "Me No Dev",
    url: "https://github.com/me-no-dev",
    avatar: "https://avatars.githubusercontent.com/u/12663778?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "ESPAsyncWebServer",
      description: "Async Web Server for ESP8266 and ESP32",
      url: "https://github.com/me-no-dev/ESPAsyncWebServer",
    },
  },
  {
    rank: 16,
    username: "felangel",
    name: "Felix Angelov",
    url: "https://github.com/felangel",
    avatar: "https://avatars.githubusercontent.com/u/8855632?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "bloc",
      description:
        "A predictable state management library that helps implement the BLoC design pattern",
      url: "https://github.com/felangel/bloc",
    },
  },
  {
    rank: 17,
    username: "alecthomas",
    name: "Alec Thomas",
    url: "https://github.com/alecthomas",
    avatar: "https://avatars.githubusercontent.com/u/41767?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "chroma",
      description: "A general purpose syntax highlighter in pure Go",
      url: "https://github.com/alecthomas/chroma",
    },
  },
  {
    rank: 18,
    username: "mikaelbr",
    name: "Mikael Brevik",
    url: "https://github.com/mikaelbr",
    avatar: "https://avatars.githubusercontent.com/u/606374?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "node-notifier",
      description:
        "A Node.js module for sending notifications on native Mac, Windows and Linux (or Growl as fallback)",
      url: "https://github.com/mikaelbr/node-notifier",
    },
  },
  {
    rank: 19,
    username: "borkdude",
    name: "Michiel Borkent",
    url: "https://github.com/borkdude",
    avatar: "https://avatars.githubusercontent.com/u/284934?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "scittle",
      description:
        "The Small Clojure Interpreter exposed for usage in script tags.",
      url: "https://github.com/borkdude/scittle",
    },
  },
  {
    rank: 20,
    username: "devongovett",
    name: "Devon Govett",
    url: "https://github.com/devongovett",
    avatar: "https://avatars.githubusercontent.com/u/19409?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "dprint-node",
      description:
        "A node API for the dprint TypeScript and JavaScript code formatter",
      url: "https://github.com/devongovett/dprint-node",
    },
  },
  {
    rank: 21,
    username: "blakeblackshear",
    name: "Blake Blackshear",
    url: "https://github.com/blakeblackshear",
    avatar: "https://avatars.githubusercontent.com/u/569905?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "frigate",
      description: "NVR with realtime local object detection for IP cameras",
      url: "https://github.com/blakeblackshear/frigate",
    },
  },
  {
    rank: 22,
    username: "paulmillr",
    name: "Paul Miller",
    url: "https://github.com/paulmillr",
    avatar: "https://avatars.githubusercontent.com/u/574696?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "chokidar",
      description: "Minimal and efficient cross-platform file watching library",
      url: "https://github.com/paulmillr/chokidar",
    },
  },
  {
    rank: 23,
    username: "minad",
    name: "Daniel Mendler",
    url: "https://github.com/minad",
    avatar: "https://avatars.githubusercontent.com/u/50754?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "consult",
      description: "consult.el - Consulting completing-read",
      url: "https://github.com/minad/consult",
    },
  },
  {
    rank: 24,
    username: "BurntSushi",
    name: "Andrew Gallant",
    url: "https://github.com/BurntSushi",
    avatar: "https://avatars.githubusercontent.com/u/456674?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "ripgrep",
      description:
        "ripgrep recursively searches directories for a regex pattern while respecting your gitignore",
      url: "https://github.com/BurntSushi/ripgrep",
    },
  },
  {
    rank: 25,
    username: "JaeYeopHan",
    name: "Jbee",
    url: "https://github.com/JaeYeopHan",
    avatar: "https://avatars.githubusercontent.com/u/17924127?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "Interview_Question_for_Beginner",
      description:
        "👦👧Technical-Interview guidelines written for those who started studying programming. I wish you all the best.👾",
      url: "https://github.com/JaeYeopHan/Interview_Question_for_Beginner",
    },
  },
];

export const repos = [
  {
    rank: 1,
    username: "jina-ai",
    repositoryName: "jina",
    url: "https://github.com/jina-ai/jina",
    description: "An easier way to build neural search on the cloud",
    language: "Python",
    languageColor: "#3572A5",
    totalStars: 5229,
    forks: 503,
    starsSince: 473,
    since: "daily",
    builtBy: [
      {
        username: "hanxiao",
        url: "https://github.com/hanxiao",
        avatar: "https://avatars.githubusercontent.com/u/2041322?s=40&v=4",
      },
      {
        username: "jina-bot",
        url: "https://github.com/jina-bot",
        avatar: "https://avatars.githubusercontent.com/u/62694369?s=40&v=4",
      },
      {
        username: "JoanFM",
        url: "https://github.com/JoanFM",
        avatar: "https://avatars.githubusercontent.com/u/19825685?s=40&v=4",
      },
      {
        username: "nan-wang",
        url: "https://github.com/nan-wang",
        avatar: "https://avatars.githubusercontent.com/u/4329072?s=40&v=4",
      },
      {
        username: "alexcg1",
        url: "https://github.com/alexcg1",
        avatar: "https://avatars.githubusercontent.com/u/4182659?s=40&v=4",
      },
    ],
  },
  {
    rank: 2,
    username: "willmcgugan",
    repositoryName: "rich",
    url: "https://github.com/willmcgugan/rich",
    description:
      "Rich is a Python library for rich text and beautiful formatting in the terminal.",
    language: "Python",
    languageColor: "#3572A5",
    totalStars: 26642,
    forks: 813,
    starsSince: 34,
    since: "daily",
    builtBy: [
      {
        username: "willmcgugan",
        url: "https://github.com/willmcgugan",
        avatar: "https://avatars.githubusercontent.com/u/554369?s=40&v=4",
      },
      {
        username: "nathanrpage97",
        url: "https://github.com/nathanrpage97",
        avatar: "https://avatars.githubusercontent.com/u/33010515?s=40&v=4",
      },
      {
        username: "apps/dependabot",
        url: "https://github.com/apps/dependabot",
        avatar: "https://avatars.githubusercontent.com/in/29110?s=40&v=4",
      },
      {
        username: "hedythedev",
        url: "https://github.com/hedythedev",
        avatar: "https://avatars.githubusercontent.com/u/50042066?s=40&v=4",
      },
      {
        username: "amartya-dev",
        url: "https://github.com/amartya-dev",
        avatar: "https://avatars.githubusercontent.com/u/49491061?s=40&v=4",
      },
    ],
  },
];
